---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  mysql
  database: cayox_dev
  username: root
  password:
  host: localhost

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...

test:
  <<:       *defaults
  database: cayox_test

  # repositories:
  #   repo1:
  #     database: sample_1_test.db

production:
  <<:       *defaults
  database: ruby_project
  username: ivan_ruby
  password: Zw;yov3XnN

  # repositories:
  #   repo1:
  #     database: sample_production.db

rake:
  <<: *defaults
